version: '3.8'

services:
      backend:
          build:
            context: ./Backend/app
            dockerfile: src/main/docker/Dockerfile.jvm
          image: backend
          volumes: 
            - storage:/backend
          ports: 
            - 8080:8080

      frontend:
          build: ./Frontend
          image: frontend
          volumes:
            - storage:/frontend
          ports:
            - 8081:8081
          depends_on:
            - backend

volumes:
    storage: